# Application Configuration
spring.application.name=gateway-service
server.port=8078

# Simple Direct Route for all requests to chombre
spring.cloud.gateway.routes[0].id=chombre-all
spring.cloud.gateway.routes[0].uri=http://chombre:8089
spring.cloud.gateway.routes[0].predicates[0]=Path=/**
spring.cloud.gateway.routes[0].filters[0]=PreserveHostHeader

# Logging Configuration
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG 