-- Insert sample chombres
INSERT INTO CHOMBRE (NUMERO_CHOMBRE, TYPE_CHOMBRE, AVERAGE_RATING, TOTAL_RATINGS) VALUES (101, 'SINGLE', 0.0, 0);
INSERT INTO CHOMBRE (NUMERO_CHOMBRE, TYPE_CHOMBRE, AVERAGE_RATING, TOTAL_RATINGS) VALUES (102, 'DOUBLE', 0.0, 0);
INSERT INTO CHOMBRE (NUMERO_CHOMBRE, TYPE_CHOMBRE, AVERAGE_RATING, TOTAL_RATINGS) VALUES (103, 'SUITE', 0.0, 0);
INSERT INTO CHOMBRE (NUMERO_CHOMBRE, TYPE_CHOMBRE, AVERAGE_RATING, TOTAL_RATINGS) VALUES (201, 'SINGLE', 0.0, 0);
INSERT INTO CHOMBRE (NUMERO_CHOMBRE, TYPE_CHOMBRE, AVERAGE_RATING, TOTAL_RATINGS) VALUES (202, 'DOUBLE', 0.0, 0);

-- Insert sample ratings
INSERT INTO RATING (SCORE, COMMENT, USER_IDENTIFIER, CHOMBRE_ID, RATING_DATE) 
VALUES (5, 'Great room, very comfortable', 'user123', 1, CURRENT_TIMESTAMP());
INSERT INTO RATING (SCORE, COMMENT, USER_IDENTIFIER, CHOMBRE_ID, RATING_DATE) 
VALUES (4, 'Nice view and clean', 'user456', 1, CURRENT_TIMESTAMP());
INSERT INTO RATING (SCORE, COMMENT, USER_IDENTIFIER, CHOMBRE_ID, RATING_DATE) 
VALUES (3, 'Average experience', 'user789', 2, CURRENT_TIMESTAMP()); 