spring.application.name=ApiJob
server.port=8093
# eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

#management.endpoints.web.exposure.include=*


spring.cloud.gateway.routes[0].id=candidat
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/candidats/**

spring.cloud.gateway.routes[1].id=job
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/jobs/**

spring.cloud.gateway.routes[2].id=MsFoyer
spring.cloud.gateway.routes[2].uri=lb://MsFoyer
spring.cloud.gateway.routes[2].predicates[0]=Path=/microService/**

logging.level.org.springframework.cloud.gateway=debug
logging.level.reactor.netty.http.client=debug