spring.application.name=MsFoyer
#DB configuration:
spring.datasource.url=jdbc:mysql://localhost:3306/msDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Web Server (tomcat) configuration :
server.port=8089
server.servlet.context-path=/microService

#eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

#Api google-map
google.maps.api.key=AIzaSyBNjla3BtN-ZoQ9LiIofGYlUNaX17xLy4g
